app/components/human-url.js

The `URL` API is not supported in IE11 and this is the next best thing to a regex (although it still involves some regex).
Why this came up:
I was working with an accessibility developer who was testing with JAWS in IE11. They asked “where do I find out about addons” to which I replied “emberobserver.com” to which *they* replied “it doesn’t seem to link to the projects repos…”.
Before:
After:

Use old-school a.href trick to get URL parts

---

app/mirage/config.js
app/mirage/factories/addon.js
app/mirage/factories/readme.js
app/models/addon.js
app/models/readme.js
app/styles/_addons_show.scss
app/templates/addons/show.hbs
tests/acceptance/addons-test.js

- Display addon's readme on the show route and make it look pretty
- Guard against missing readme (this can be deployed independently of the server change, and there also are some addons without readmes when I fetch data in development.. let me know if you'd prefer a "readme data unavailable" message instead)
- Make the mirage config return a single addon rather than an array for the queryRecord response. This removes a deprecation warning and matches the real server response
- Fix a minor typo on the addons show route ('Official')

Show addon readmes

---

app/templates/about.hbs

Hi everyone, 
thanks for this repo, I'm learning Ember from it.
Saw a little typo in the text... `somepoint` → `some point`.
Cheers!
Gus

Fix typo in template for about

---

app/adapters/application.js
app/utils/network-cache.js

@locks and I worked on this the other day. The overarching goal is to use emberobserver as a public real world performance benchmark. I have more changes to upstream but I got disrupted by a fire alarm this morning, so this is the first piece 😅 
This commit adds a simple utility for capturing network requests into local storage and playing them back later for a subsequent page load. This is useful for benchmarking where you would like to remove as much variables as possible (network requests in this case) to keep the runs consistent.
To use this, simply add `?perf.capture` to the URL. Once the page has loaded you can navigate to `?perf.playback` and see that all network requests were served from the local cache.
Currently, this requires manually wrapping the places where we are making …

Add a local network cache for benchmarking

---

package.json

There is a performance regression with the latest Ember beta that was addressed in Ember Data 2.8.1 (https://github.com/emberjs/data/pull/4545).

Bump ember-data

---

app/index.html
public/opensearch.xml

[Opensearch](http://www.opensearch.org/) is a way to describe a search engine.
This adds the ability to search on Ember observer from the url bar on [most browsers](http://www.opensearch.org/Community/OpenSearch_search_clients).
Developers can take advantage of opensearch to speed up their search for an addon.
1. Go to emberobserver.com and wait for SPA to load
2. Type query
3. Find results
1. type `emberobserver.com` characters (URL Bar) until you get chrome to autocomplete `emberobser.com` and hit tab
2. type addon name
3. Find results
**Extra notes**
I find it particularly useful when searching on Google, Facebook, Github and many other websites that have opensearch implemented.
Not everyone uses this, but for everyone else that does it makes it super useful.

[WIP] Adds opensearch

---

server/proxies/api.js

Small change to set the mock API proxy from "localhost:3000" to "emberobserver.com" and enable a functional local dev environment for new contributors.

Fixes issue with mock api proxy url

---

app/styles/_loading.scss
app/styles/app.scss
app/templates/addons/loading.hbs
app/templates/categories/loading.hbs
app/templates/lists/loading.hbs
app/templates/maintainers/loading.hbs

Resolves issue #72:
* adds [ember-spin-kit](https://github.com/angelomachado/ember-spin-kit) addon (additional CSS dependency)
* adds loading templates to `addons`, `categories`, `lists` and `maintainers` routes, which seemed to be the most critical cases. it could a be general `loading` template on the `application` level, but that's more of a design/UX question, if you really want to show loading on everything.

Adds loading templates to long-loading routes 

---

app/styles/_loading.scss

Amends #77.
Just noticed a the `margin-top` looked a little funny when dev-tools where off and the footer had a different height. This change makes the spinner appear a little more consistent across the routes where it's applied.

Minor top margin fix for loading spinner

---

app/templates/components/addon-source-usages.hbs
tests/acceptance/code-search-test.js

The code search has been incredibly useful for my work on [ember-typings](https://github.com/typed-ember/ember-typings). It's almost like having API documentation! Links would make it even better
Fixes #89

code search: link to the matched source code

---

app/components/addon-source-usages.js
app/components/code-search.js
app/controllers/code-search.js
app/services/code-search.js
app/styles/components/_code-search.scss
app/templates/code-search.hbs
app/templates/components/code-search.hbs
config/environment.js
tests/acceptance/code-search-test.js

- Add ability to filter code search results down to addons with at least one file matching the given regex (requires corresponding API change)
- Filter usages down to those with file path matching the filter regex
- Show spinner in results area while sorting or changing filter to avoid awkward jumping
- Add file path filter input to UI and restyle
- Fixes a bug where 'See more results' remained visible on last page of results

Code search result filtering take 2

---

app/models/ember-versions.js
app/serializers/ember-versions.js
app/services/ember-versions.js
config/environment.js
mirage/config.js
mirage/models/ember-versions.js
package.json
tests/.eslintrc.js
tests/acceptance/addons-test.js
tests/unit/services/ember-versions-test.js
yarn.lock

- Added `emberVersions` model
- New model has a "githubResponse" attribute, I learned that "data" is a protected name for DS.Model attributes.
- `JSONAPISerializer` was resolving payload oddly because of pluralized model name, so I added a ember-versions serializer as a workaround.
- Installed ember-feature-flags

Replaced direct Github API access

---

app/components/code-search.js
app/services/code-search.js
app/templates/components/code-search.hbs
tests/acceptance/code-search-test.js

This PR addresses half of the #99 feature request.
- Sorting button behind `code-search-score-sorting` feature flag
- `/search/addons` endpoint will need to include `score` in results (doesn't currently appear to)

Added new sorting to code search results

---

app/helpers/clean-repo-url.js
app/templates/components/addon-source-usages.hbs
tests/acceptance/code-search-test.js
tests/integration/helpers/clean-repo-url-test.js

Remove trailing '.git' from repo URLs in code search

---

app/styles/_login.scss

#118 
First of a few PR's to remove [Neat](https://neat.bourbon.io/) in favour of flexbox.
Mobile:
Desktop:
Mobile: 
Desktop:

Removed neat usage from login

---

app/styles/_addons_show.scss

Part of #118 
The readme class is on a `<section>` element so it assumes its parent's width without needing to apply `@include span-columns(12)`.

Removed neat grid usage from addon readme's

---

.bowerrc

Because bower and the bower registry have been deprecated, manually specifying the registry location is required to avoid 502 errors during install.

Resolve bower deprecation issue

---

.bowerrc
.circleci/config.yml
README.md
app/styles/app.scss
app/styles/base/_grid-settings.scss
bower.json
config/ember-try.js
package.json
yarn.lock

I moved bourbon and neat from bower packages to npm packages and removed bower from project. 
But I am not sure how will the tests work.

Removing bower

---

package.json
tests/acceptance/addons-test.js
tests/acceptance/admin-review-addon-test.js
tests/acceptance/admin-test.js
tests/acceptance/build-results-test.js
tests/acceptance/canary-test-results-test.js
tests/acceptance/code-search-test.js
tests/acceptance/index-test.js
tests/acceptance/maintainers-test.js
tests/acceptance/managing-build-servers-test.js
yarn.lock

[Percy](https://percy.io/) is a visual testing tool designed to help catch regressions and reduce the amount of manual testing done in your application. 
With Percy's recent introduction of a [free plan](https://blog.percy.io/introducing-our-free-visual-testing-plan-2cd70a34d89d) and some important CSS changes [planned](https://github.com/emberobserver/client/issues/118) for Ember Observer, Percy now makes a lot of sense.
This PR:
- installs `ember-percy`, an ember addon used to easily integrate Percy into ember projects
- adds percy snapshots to some of the most commonly accessed pages of the application
- `ember-percy` repo is [here](https://github.com/percy/ember-percy/).
- `PERCY_TOKEN` has already been added to the CI env so snapshots for master will hopefully just begin being taken …

Added percy integration

---

.vscode/launch.json
ember-cli-build.js
package.json
yarn.lock

This switches the build to [embroider](https://github.com/embroider-build/embroider). All tests should be passing and the whole app is working normally as far as I can tell.
This PR also enables fully static component and helper resolution, meaning all unused components and helpers in the app and addons will shake out of the build. 
The total size impact is modest, as there wasn't a ton of unused stuff in this app. But it's a necessary first step toward what I want to enable next, which is route-based splitting.

Build with embroider

---

app/app.js
package.json
yarn.lock

Two things were broken with ember-metrics.
First, it does dynamic container lookup of its adapters, which I'm working around here by explicitly importing and defining the ones we need. (A way to do this directly from packageRules in embroider will be forthcoming.)
Second, the addon itself actually contained invalid usage of import & export. See https://github.com/poteto/ember-metrics/pull/221

fixing ember-metrics under embroider

---

app/routes/categories/show.js
tests/acceptance/categories-test.js

This test passes, but it does so in a way that's probably not what was intended:
1. The `application` route makes a *real* network request, which fails. 
2. The `categories.show` route tries to chain off that failed promise and gets the rejection.
That doesn't really test the case of a nonexistent category, it tests the case of being unable to load any categories.
This change activates mirage instead, so that a *fake* network request in the `application` route succeeds, and then the code within the `categories.show` route can get exercised and deal with the case where the category doesn't exist.
This error was harmless for users, but it's messing up my embroider testing because when we're lazy-loading the categories routes, the rejected promise in the `application` route goes un-observed …

Remove accidental network request from test suite

---

app/components/build-result-output.js
app/components/test-result-status.js
app/controllers/admin/build-results/show.js
app/controllers/canary-test-results/date.js
app/controllers/canary-test-results/detail.js
app/models/test-result.js
app/styles/_admin_build_result.scss
app/styles/app.scss
app/styles/components/_build-result-output.scss
app/templates/admin/build-results/show.hbs
app/templates/canary-test-results/detail.hbs
app/templates/components/build-result-output.hbs
app/templates/components/test-result-status.hbs
tests/integration/components/build-result-output-test.js

This updates the frontend to handle JSON-formatted test result data (see https://github.com/emberobserver/server/pull/66). This allows the result data to be displayed in a nested/collapsible form, with output grouped to the command that generated it. The styling could use some work but I don't think it's any worse than what we're doing currently.

Handle JSON-formatted test output

---

app/components/dependency-table.js
app/components/dependency-tables.js
app/models/version.js
app/styles/components/_dependency-table.scss
app/templates/addons/show.hbs
app/templates/components/dependency-table.hbs
app/templates/components/dependency-tables.hbs
tests/acceptance/addons-test.js

Requires backend PR: https://github.com/emberobserver/server/pull/62
This adds a Dependents section to the addon page that lists non-hidden addons where the latest version has any version of this addon as a dependency. Dependent addon data is loaded when the 'Show addons' link is clicked.
- Make `dependency-table` component reusable for dependent addons. Add `dependency-tables` component that wraps a `dependency-table` each for dependencies and dependents.
- Add `addonName` property to `version` model.
- Upgrade qunit to access `setupOnerror` and `resetOnerror` methods.
Before loading:
After loading:
No dependents:
Error loading:

Show dependent addons

---

package.json
yarn.lock

Hi!  I noticed an issue in the ember-data test run and it seems like this global namespace clash is effecting a lot of libraries.  We can certainly patch the version when we run the partner tests if you are not comfortable with this change!
Details here -
https://github.com/emberjs/data/pull/7264

Fix ember-fetch error with latest whatwg global namespace issue

---

app/styles/components/_large-search.scss

This PR is to fix the "no result" label that is invisible for the user
--Before--
--After--

Fix invisible no result label

---

README.md
app/components/page-layout.hbs
app/styles/components/_page-layout.scss
public/ember-observer.svg

In discussion with @kategengler I've created and added a new logo to the header :)
PS: Also edited the readme to say yarn instead of nom :)

Adds new Ember observer logo to header

---

app/components/addon-details.hbs
app/components/addon-details.js

Convert the `<AddonDetails />` component to be a template-only Glimmer component. This was an easy one since there was nothing actually happening on the backing class (other than the argument reflection).

Convert <AddonDetails/> into a template-only Glimmer component

---

app/components/dependency-size.js
app/components/dependency-table.hbs
app/components/dependency-tables.js
app/helpers/format-bytes.js
app/models/addon-dependency.js
app/models/addon-size.js
app/models/version.js
app/styles/app.scss
app/styles/components/_dependency-size.scss
app/templates/components/dependency-size.hbs
app/utils/normalize-fingerprinted-asset.js
mirage/factories/addon-size.js
mirage/models/addon-dependency.js
mirage/models/addon-size.js
mirage/models/version.js
tests/acceptance/addons-test.js
tests/integration/components/dependency-size-test.js
tests/integration/helpers/format-bytes-test.js
tests/unit/utils/normalize-fingerprinted-asset-test.js

Show addon dependency sizes (when available)
Requires server PR: https://github.com/emberobserver/server/pull/82
- Add package addon relationship to addon dependency
- When fetching dependencies, sideload addon size for the most recent version of the dependency
- Show total size next to dependency name; clicking expands to show details
- Clicking 'other assets' row expands to show filenames and sizes for files outside of app/vendor

Show addon dependency sizes

---

app/components/admin-addon.hbs
app/components/relative-time.hbs
app/components/relative-time.js
app/routes/canary-test-results/index.js
app/services/current-date.js
tests/acceptance/addons-test.js
tests/acceptance/admin-review-addon-test.js
tests/acceptance/canary-test-results-test.js
tests/acceptance/size-calculation-results-test.js
tests/integration/components/relative-date-test.js

Fixes #146 
This PR makes some tests (a subset of the ones that include `percySnapshot` calls) to use static/fixed data to avoid showing visual changes just because of a different date.
There were two tests that couldn't be fixed just by using static data:
1) `Acceptance | admin review addon: Displays basic info about addon` - the `<AdminAddon/>` component used `{{moment-from-now}}` to display a relative interval (relative to the current date/time)
2) `Acceptance | canary test results: redirects to current day` - the redirection from `canary-test-results.index` to `canary-test-results.show` is based on the current date, which is rendered in the page
To get these to stop changing in Percy I added a `currentDate` service; its `date` property normally returns the actual current date, but a …

Use static data in tests to avoid Percy showing changes that aren't meaningful
